# PHSX 256 Topic 6: Array-Like Objects

## Setup

In [1]:
import numpy as np
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.



## Array‑like objects and vectors

Python offers several *array‑like* containers:
- **List**: `[1, 2, 3]` (flexible, can hold mixed types)
- **Tuple**: `(1, 2, 3)` (immutable)
- **Range**: `range(0, 5)` (sequence of integers)
- **NumPy array**: `np.array([1, 2, 3])` (homogeneous numeric type, enables vectorized math)

In mechanics, we represent vectors (e.g., position, velocity) as small **NumPy arrays**, e.g. `np.array([x, y])` or `np.array([x, y, z])`.


In [ ]:
# Examples of array-like objects
py_list = [1, 2, 3]
py_tuple = (1, 2, 3)
py_range = range(0, 4)
np_array = np.array([1, 2, 3])

print("List        :", py_list)
print("Tuple       :", py_tuple)
print("Range -> list:", list(py_range))
print("NumPy array :", np_array, type(np_array))

### Simple vector usage (2D)
We will treat $\vec{r}=(x,y)$ and $\vec{v}=(v_x,v_y)$ as length‑2 arrays and compute magnitudes.

In [ ]:
r = np.array([3.0, 4.0])     # position vector (x, y)
v = np.array([2.0, -1.0])    # velocity vector (vx, vy)

# Magnitudes (Euclidean norms)
r_mag = np.linalg.norm(r)
v_mag = np.linalg.norm(v)

print("r =", r, "|r| =", r_mag)
print("v =", v, "|v| =", v_mag)


## Arrays vs. Lists (and broadcasting)

- **Lists** are general‑purpose containers. Using `+` **concatenates** lists.
- **NumPy arrays** support fast, vectorized **elementwise** math and **broadcasting**.

Broadcasting example: if $m$ is scalar mass and $\vec{a}$ is acceleration, then $\vec{F}=m\,\vec{a}$ applies componentwise.


In [ ]:
# List vs array behavior for + and *
L1, L2 = [1, 2, 3], [4, 5, 6]
a1, a2 = np.array(L1), np.array(L2)

print("List + List      ", L1 + L2)      # concatenation
print("Array + Array    ", a1 + a2)      # elementwise addition
print("List * 3         ", L1 * 3)       # repetition
print("Array * 3        ", a1 * 3)       # scalar multiplication

# Broadcasting (scalar times vector)
m = 2.0
acc = np.array([0.0, -9.81])
force = m * acc
print("F = m a ->", force)


## Making arrays — comprehensive examples

Below are common ways to construct arrays. We'll print the **values**, **shape**, and **dtype** so you can see the differences.


In [5]:
# 3.1 From Python data
A_list = np.array([1, 2, 3])                      # 1D from list
A_nested = np.array([[1, 2, 3], [4, 5, 6]], float) # 2D from nested list with dtype
A_tuple = np.array((7, 8, 9))                      # from tuple

print("A_list:", A_list, A_list.shape, A_list.dtype)
print("A_nested:", A_nested, A_nested.shape, A_nested.dtype)
print("A_tuple:", A_tuple, A_tuple.shape, A_tuple.dtype)

# 3.2 asarray vs array (views vs copies when possible)
B_src = [10, 11, 12]
B1 = np.asarray(B_src)   # view when possible (no copy if already ndarray)
B2 = np.array(B_src)     # makes an array (may copy)
print("asarray:", B1, B1.base is None)
print("array  :", B2, B2.base is None)

# 3.3 Ranges and spaced arrays
ar = np.arange(0, 7, 2)                  # 0,2,4,6
lin = np.linspace(0.0, 1.0, 5)           # inclusive endpoints
log = np.logspace(0, 3, 4, base=10.0)    # 10^0 .. 10^3, 4 points
geo = np.geomspace(1, 1000, 4)           # geometric progression
print("arange:", ar)
print("linspace:", lin)
print("logspace:", log)
print("geomspace:", geo)

# 3.4 Zeros/ones/full and *_like variants
Z = np.zeros((2,3), dtype=float)
O = np.ones((2,3), dtype=int)
F = np.full((2,3), 7.5)
ZL = np.zeros_like(A_nested)
OL = np.ones_like(A_nested)
FL = np.full_like(A_nested, fill_value=-1)
print("zeros:", Z)
print("ones:", O)
print("full:", F)
print("zeros_like:", ZL)
print("ones_like:", OL)
print("full_like:", FL)

# 3.5 Identity/diagonal helpers (2D only)
E = np.eye(3)
D = np.diag([1, 2, 3])
print("eye:", E)
print("diag:", D)

# 3.6 Random arrays (using Generator API)
rng = np.random.default_rng(42)
U = rng.random((2,3))                 # uniform [0,1)
Nrm = rng.normal(loc=0.0, scale=1.0, size=(2,3))
Int = rng.integers(low=0, high=10, size=(2,3))
print("random U:", U)
print("normal :", Nrm)
print("integers:", Int)

# 3.7 empty / empty_like (uninitialized memory; fill before using)
Ept = np.empty((2,3))
EptL = np.empty_like(A_nested)
print("empty (values arbitrary):", Ept)
print("empty_like (values arbitrary):", EptL)

# 3.8 dtype control and conversion (basic preview)
C_float32 = np.array([1,2,3], dtype=np.float32)
C_int64 = C_float32.astype(np.int64)
print("float32:", C_float32, C_float32.dtype)
print("astype -> int64:", C_int64, C_int64.dtype)

# 3.9 New axes (preview)
base = np.arange(6)
print("base:", base, base.shape)
col = base[:, None]   # (6,1)
print("col shape:", col.shape)
col = np.expand_dims(base, axis=1)
print("col shape:", col.shape)
row = base[None, :]   # (1,6)
print("row shape:", row.shape)
row = np.expand_dims(base, axis=0)
print("row shape:", row.shape)

A_list: [1 2 3] (3,) int32
A_nested: [[1. 2. 3.]
 [4. 5. 6.]] (2, 3) float64
A_tuple: [7 8 9] (3,) int32
asarray: [10 11 12] True
array  : [10 11 12] True
arange: [0 2 4 6]
linspace: [0.   0.25 0.5  0.75 1.  ]
logspace: [   1.   10.  100. 1000.]
geomspace: [   1.   10.  100. 1000.]
zeros: [[0. 0. 0.]
 [0. 0. 0.]]
ones: [[1 1 1]
 [1 1 1]]
full: [[7.5 7.5 7.5]
 [7.5 7.5 7.5]]
zeros_like: [[0. 0. 0.]
 [0. 0. 0.]]
ones_like: [[1. 1. 1.]
 [1. 1. 1.]]
full_like: [[-1. -1. -1.]
 [-1. -1. -1.]]
eye: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
diag: [[1 0 0]
 [0 2 0]
 [0 0 3]]
random U: [[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]
normal : [[ 0.1278404  -0.31624259 -0.01680116]
 [-0.85304393  0.87939797  0.77779194]]
integers: [[7 6 4]
 [8 5 4]]
empty (values arbitrary): [[0.1278404  0.31624259 0.01680116]
 [0.85304393 0.87939797 0.77779194]]
empty_like (values arbitrary): [[0.1278404  0.31624259 0.01680116]
 [0.85304393 0.87939797 0.77779194]]
float32: [1. 2. 3.] float32
a


## Creating multi‑dimensional arrays with `numpy.meshgrid`

`numpy.meshgrid` builds **coordinate grids** from 1D coordinate arrays. This is useful when evaluating a scalar field on a 2D/3D grid (e.g., potential energy surfaces, height fields, or density maps).

- Given 1D vectors `x` of length $N_x$ and `y` of length $N_y$, `np.meshgrid(x, y, indexing='xy')` returns two 2D arrays `X` and `Y`, each of shape $(N_y, N_x)$.
- Using `indexing='ij'` returns shapes aligned to the input order: `X, Y` have shape $(N_x, N_y)$.

**Physics example:** Evaluate the 2D isotropic harmonic potential $V(x,y)=\tfrac{1}{2}k\,(x^2+y^2)$ on a grid and plot contours.


In [ ]:

import numpy as np
import matplotlib.pyplot as plt

# 2D coordinate vectors
x = np.linspace(-5.0, 5.0, 11)   # Nx = 11
y = np.linspace(0.0, 10.0, 6)    # Ny = 6

# 'xy' indexing (default): X,Y shapes are (Ny, Nx)
X_xy, Y_xy = np.meshgrid(x, y, indexing='xy')
print('xy indexing shapes:', X_xy.shape, Y_xy.shape)

# 'ij' indexing: X,Y shapes are (Nx, Ny)
X_ij, Y_ij = np.meshgrid(x, y, indexing='ij')
print('ij indexing shapes:', X_ij.shape, Y_ij.shape)

# Evaluate a scalar field on the grid: 2D harmonic potential V(x,y) = 1/2 * k * (x^2 + y^2)
k = 1.0
V = 0.5 * k * (X_xy**2 + Y_xy**2)   # shape (Ny, Nx)

plt.figure(figsize=(5.5,4))
cs = plt.contourf(X_xy, Y_xy, V, levels=15, cmap='viridis')
plt.colorbar(cs, label='V(x,y)')
plt.xlabel('x')
plt.ylabel('y')
plt.title('2D harmonic potential on a meshgrid (indexing='xy')');

# Flattening a grid to a list of points (useful for vectorized function calls)
pts = np.column_stack([X_xy.ravel(), Y_xy.ravel()])  # shape (Ny*Nx, 2)
print('points array shape:', pts.shape)



### 3D grids with `meshgrid`

For three 1D arrays `x`, `y`, `z` of lengths $N_x$, $N_y$, $N_z$, call `np.meshgrid(x, y, z, indexing='ij')` to obtain `X`, `Y`, `Z` with shapes $(N_x, N_y, N_z)$. This keeps axis order consistent and is often convenient for physics problems.

**Example:** Sample the softened point‑mass gravitational potential $\Phi(x,y,z) = -\dfrac{GM}{\sqrt{x^2+y^2+z^2+\varepsilon}}$ on a 3D grid.


In [ ]:

import numpy as np

G = 6.674e-11
M = 5.97e24

eps = 1.0  # softening to avoid division by zero (units arbitrary here)

x = np.linspace(-2.0, 2.0, 10)
y = np.linspace(-2.0, 2.0, 10)
z = np.linspace(-2.0, 2.0, 10)

X, Y, Z = np.meshgrid(x, y, z, indexing='ij')   # shapes (Nx, Ny, Nz)

R = np.sqrt(X**2 + Y**2 + Z**2 + eps)
Phi = -G * M / R

print('X,Y,Z shapes:', X.shape, Y.shape, Z.shape)
print('Phi shape:', Phi.shape, '| min/max:', float(Phi.min()), float(Phi.max()))

# Extract a central slice (z ~ 0) for quick 2D visualization
z_mid = Z.shape[2] // 2
Phi_slice = Phi[:, :, z_mid]

import matplotlib.pyplot as plt
plt.figure(figsize=(5.5,4))
plt.imshow(Phi_slice.T, origin='lower', extent=[x.min(), x.max(), y.min(), y.max()],
           aspect='auto', cmap='magma')
plt.colorbar(label='Phi(x,y, z=mid)')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Central z-slice of 3D gravitational potential');



## Reshaping arrays (views vs copies, new axes, squeeze)

Reshaping changes the *shape* but not the total number of elements. Common tools:
- `reshape(new_shape)`: returns a **view** when possible; may return a copy.
- "Auto" dimension with `-1` lets NumPy infer one dimension from the others.
- `np.ravel(a)`: returns a **flattened view** when possible; copy otherwise.
- `a.flatten()`: returns a **copy** (always).
- Add/remove axes: `np.expand_dims(a, axis=...)`, `a[:, None]`, `np.squeeze(a, axis=...)`.
- Memory order: `order='C'` (row-major) or `order='F'` (column-major) can affect how data are read; shapes are the same, but memory layout matters for performance.

Below are practical examples and shape checks.


In [ ]:
# 4.1 reshape with explicit shapes
arr = np.arange(12)
A34 = arr.reshape(3, 4)          # (3,4)
A26 = arr.reshape(2, 6)          # (2,6)
print("arr:", arr, arr.shape)
print("reshape (3,4):", A34)
print("reshape (2,6):", A26)

# 4.2 reshape with -1 (auto) and memory order
A_auto = arr.reshape(-1, 3)       # infer first dim -> (4,3)
A_C = arr.reshape(3,4, order='C')
A_F = arr.reshape(3,4, order='F')
print("reshape (-1,3):", A_auto, A_auto.shape)
print("order='C':", A_C)
print("order='F':", A_F)

# 4.3 ravel vs flatten and .base check (view vs copy)
raveled = np.ravel(A34)           # view if possible
flattened = A34.flatten()         # copy
print("raveled shares data?", raveled.base is not None)
print("flattened shares data?", flattened.base is not None)

# Modify A34 and see ravel reflect changes (if it was a view)
A34[0,0] = 999
print("A34 after edit:", A34)
print("raveled after edit:", raveled)
print("flattened after edit:", flattened)

# 4.4 add/remove axes: expand_dims, newaxis, squeeze
b = np.arange(5)              # (5,)
col = b[:, None]              # (5,1)
row = b[None, :]              # (1,5)
col2 = np.expand_dims(b, 1)   # (5,1)
row2 = np.expand_dims(b, 0)   # (1,5)
restored = np.squeeze(col, axis=1)   # back to (5,)
print("b:", b, b.shape)
print("col:", col.shape, "row:", row.shape)
print("expand_dims -> col2, row2:", col2.shape, row2.shape)
print("squeeze ->", restored.shape)

# 4.5 reshape pitfalls: incompatible sizes
try:
    bad = np.arange(10).reshape(3,4)   # 10 != 12 elements
except ValueError as e:
    print("Expected ValueError:", e)


## Changing dtype (precision, casting, and conversions)

Ways to control or change dtype:
- Specify `dtype=` when **creating** arrays.
- Use `astype(new_dtype)` to **convert** (returns a **copy** by default).
- `astype(new_dtype, copy=False)` *may* avoid copying if no change is needed.
- Converting to lower precision or to integers may **lose information** (e.g., truncation).
- For safety, `astype(..., casting='safe')` disallows unsafe conversions.

Examples below illustrate common cases and caveats.


In [ ]:

# 5.1 dtype on creation
x_f64 = np.array([1.2, 3.4, 5.6], dtype=np.float64)
x_i32 = np.array([1, 2, 3], dtype=np.int32)
print("x_f64:", x_f64, x_f64.dtype)
print("x_i32:", x_i32, x_i32.dtype)

# 5.2 astype conversions
x = np.array([0.9, 1.1, 2.9, -3.7])
xi = x.astype(np.int64)      # truncates toward zero
xf32 = x.astype(np.float32)  # reduced precision
print("x:", x, x.dtype)
print("x -> int64:", xi, xi.dtype)
print("x -> float32:", xf32, xf32.dtype)

# 5.3 copy=False and no-op casts
y = np.array([1,2,3], dtype=np.int32)
y2 = y.astype(np.int32, copy=False)  # no copy needed
print("same object?", y is y2)

# 5.4 safe casting guard
z = np.array([1.5, 2.5])
try:
    z_bad = z.astype(np.int32, casting='safe')
except TypeError as e:
    print("Expected TypeError (unsafe cast blocked):", e)

# 5.5 bool and float/int conversions
flag = np.array([0, 1, 2, 0]).astype(bool)
back_to_int = flag.astype(np.int8)
print("bool:", flag, flag.dtype)
print("bool -> int8:", back_to_int, back_to_int.dtype)

# 5.6 advanced caution: .view reinterprets bytes (not a numeric conversion)
# Only for demonstration; the shape may need adjustment when itemsize changes.
raw = np.array([1, 2], dtype=np.int32)
byte_view = raw.view(np.uint8)
print("raw int32:", raw, raw.dtype, "-> viewed as uint8 bytes:", byte_view, byte_view.dtype)



## Classical mechanics example: projectile motion (vectorized)

Assume constant gravitational acceleration $\vec{a}=(0,-g)$ with $g=9.81\,\text{m/s}^2$. For initial position $\vec{r}_0=(x_0,y_0)$ and initial velocity $\vec{v}_0=(v_{x0},v_{y0})$:

- $\vec{v}(t)=\vec{v}_0+\vec{a}\,t$
- $\vec{r}(t)=\vec{r}_0+\vec{v}_0\,t+\tfrac{1}{2}\,\vec{a}\,t^2$

We compute the trajectory on a time grid using vectorized arrays.


In [ ]:

# Parameters
g = 9.81
r0 = np.array([0.0, 0.0])
v0 = np.array([20.0, 20.0])
T  = 4.5
N  = 200
t  = np.linspace(0, T, N)
a  = np.array([0.0, -g])

# Broadcast over time by shaping t for elementwise operations
t_col = t[:, None]                   # shape (N,1)

v_t = v0 + a * t_col                 # (N,2)
r_t = r0 + v0 * t_col + 0.5 * a * (t_col**2)  # (N,2)

# Stop trajectory when y < 0 (hits ground)
hit = np.argmax(r_t[:,1] < 0)
if hit > 0:
    t_use = t[:hit]
    r_use = r_t[:hit]
else:
    t_use = t
    r_use = r_t

# Plot
plt.figure(figsize=(5.5,4))
plt.plot(r_use[:,0], r_use[:,1], label="trajectory")
plt.axhline(0, color='k', lw=0.8)
plt.xlabel("x (m)")
plt.ylabel("y (m)")
plt.title("Projectile motion under gravity")
plt.legend();



## Multi‑dimensional arrays: single vs. ensembles

A single trajectory `r_t` has shape `(N,2)` for $N$ time steps and components $(x,y)$. For multiple launch angles, build an **ensemble** with shape `(P,N,2)`:
- axis 0: projectile index
- axis 1: time index
- axis 2: spatial components $(x,y)$


In [ ]:

# Ensemble of projectiles with different launch angles
P = 4
speeds = np.full(P, 25.0)
angles = np.deg2rad([20, 35, 50, 65])

v0s = np.stack([speeds*np.cos(angles), speeds*np.sin(angles)], axis=1)  # (P,2)

T = 6.0
N = 300
t = np.linspace(0, T, N)
a = np.array([0.0, -9.81])

trajectories = []
for v0_i in v0s:
    t_col = t[:, None]
    r = r0 + v0_i * t_col + 0.5 * a * (t_col**2)   # (N,2)
    trajectories.append(r)

trajectories = np.stack(trajectories, axis=0)     # (P,N,2)
print("trajectories shape:", trajectories.shape)

# Plot all
plt.figure(figsize=(6,4))
for p in range(P):
    r = trajectories[p]
    valid = r[:,1] >= 0
    plt.plot(r[valid,0], r[valid,1], label=f"angle={np.rad2deg(angles[p]).astype(int)}°")
plt.axhline(0, color='k', lw=0.8)
plt.xlabel("x (m)")
plt.ylabel("y (m)")
plt.title("Ensemble of projectile trajectories")
plt.legend();



## Making and combining arrays (concatenation, stacking, tiling) — detailed

**Concatenate** merges arrays along an **existing** axis.  
**Stack** creates a **new** axis.  
Helpers: `np.vstack`, `np.hstack`, `np.dstack`, `np.column_stack`, `np.row_stack`, `np.r_`, `np.c_`.  
Repetition helpers: `np.repeat`, `np.tile`.

We will carefully show **values**, **shapes**, and **axes**.


In [ ]:
# 8.1 1D arrays: concatenate vs stack
x = np.arange(3)           # [0,1,2]  shape (3,)
y = np.arange(3, 6)        # [3,4,5]  shape (3,)

cat_xy = np.concatenate([x, y])        # shape (6,)
stk0 = np.stack([x, y], axis=0)        # shape (2,3)  NEW axis 0
i_stk1 = np.stack([x, y], axis=1)      # shape (3,2)  NEW axis 1

print("concatenate ->", cat_xy, cat_xy.shape)
print("stack axis=0 ->", stk0, stk0.shape)
print("stack axis=1 ->", i_stk1, i_stk1.shape)

# 8.2 2D arrays: concatenation along rows vs columns
A = np.arange(6).reshape(2,3)   # [[0,1,2],[3,4,5]]  shape (2,3)
B = (np.arange(6)+10).reshape(2,3)

cat_rows = np.concatenate([A, B], axis=0)   # stacks rows -> shape (4,3)
cat_cols = np.concatenate([A, B], axis=1)   # stacks columns -> shape (2,6)
print("A=", A)
print("B=", B)
print("concat rows (axis=0):", cat_rows, cat_rows.shape)
print("concat cols (axis=1):", cat_cols, cat_cols.shape)

# 8.3 vstack / hstack / dstack
v_stk = np.vstack([x, y])                  # (2,3); same as stack axis=0 for 1D
h_stk = np.hstack([x, y])                  # (6,) ; same as concatenate for 1D
D1 = np.arange(6).reshape(1,3,2)
D2 = np.arange(6,12).reshape(1,3,2)
d_stk = np.dstack([D1[0], D2[0]])          # stack along depth -> (3,2,2)
print("vstack ->", v_stk, v_stk.shape)
print("hstack ->", h_stk, h_stk.shape)
print("dstack shape:", d_stk.shape)

# 8.4 column_stack / row_stack
X = np.linspace(0, 2*np.pi, 5)
Y = np.sin(X)
pts = np.column_stack([X, Y])   # (5,2)
rows = np.row_stack([X, Y])     # (2,5)
print("column_stack points=", pts, pts.shape)
print("row_stack rows=", rows, rows.shape)

# 8.5 np.r_ and np.c_ (convenience)
r_cat = np.r_[x, y]             # concatenate 1D
c_col = np.c_[X, Y]             # like column_stack
print("np.r_ ->", r_cat, r_cat.shape)
print("np.c_ ->", c_col, c_col.shape)

# 8.6 repeat and tile (construct larger arrays by repetition)
base = np.array([1, 2, 3])
rep = np.repeat(base, repeats=[1,2,3])   # [1, 2,2, 3,3,3]
tiled = np.tile(base, reps=3)            # [1,2,3,1,2,3,1,2,3]
print("repeat ->", rep)
print("tile   ->", tiled)


## Classical mechanics example: simple harmonic oscillator (SHO)

For amplitude $A$, angular frequency $\omega$, and phase $\phi$:

- $x(t)=A\cos(\omega t+\phi)$
- $v(t)=-A\omega\sin(\omega t+\phi)$

We can stack $x$ and $v$ to form a state array.


In [ ]:
A = 2.0
omega = 3.0
phi = 0.3

T = 4.0
N = 400
t = np.linspace(0, T, N)

x = A*np.cos(omega*t + phi)
v = -A*omega*np.sin(omega*t + phi)
state = np.column_stack([x, v])   # (N,2)

plt.figure(figsize=(6,3))
plt.plot(t, x, label='x(t)')
plt.plot(t, v, label='v(t)')
plt.xlabel('time (s)')
plt.title('SHO: position and velocity')
plt.legend();

# Phase portrait
plt.figure(figsize=(4,4))
plt.plot(x, v)
plt.xlabel('x')
plt.ylabel('v')
plt.title('Phase portrait');


## Practice problems

**Problem 1 — Constant‑acceleration kinematics (vector form).**  
A particle has constant acceleration $\vec{a}=(a_x,a_y)$. Given $\vec{r}_0$ and $\vec{v}_0$, compute arrays for $\vec{r}(t)$ and $\vec{v}(t)$ on a time grid using $\vec{v}(t)=\vec{v}_0+\vec{a}\,t$ and $\vec{r}(t)=\vec{r}_0+\vec{v}_0\,t+\tfrac{1}{2}\,\vec{a}\,t^2$. Stack into $[x,y,v_x,v_y]$ with `np.column_stack`.

**Problem 2 — Energy of a projectile (no air).**  
For mass $m$ and trajectory $(x(t),y(t))$ with speed $v(t)$, compute $K(t)=\tfrac{1}{2}m\,v(t)^2$ and $U(t)=mg\,y(t)$. Plot $E(t)=K(t)+U(t)$ vs time. (Use numerical derivatives from your array samples for $v(t)$ if you like.)

**Problem 3 — Array creation toolbox.**  
Create each of the following with shapes you choose: `np.arange`, `np.linspace`, `np.logspace`, `np.geomspace`, `np.zeros`, `np.ones`, `np.full`, `np.zeros_like`, `np.ones_like`, `np.full_like`, `np.eye`, `np.diag`, and random arrays from a `Generator`. For each, print the value, shape, and dtype.

**Problem 4 — Reshaping practice.**  
Given a 1D array of length $N$, reshape it into shapes $(N,1)$, $(1,N)$, $(a,b)$ with $ab=N$, and flatten it back using both `ravel` and `flatten`. Verify which results share memory with the original by checking `.base`.

**Problem 5 — Dtype conversions.**  
Starting from floats, produce an integer array with `astype`, then convert to `float32` and back to `float64`. Comment on information loss and how to detect it (e.g., compare against the original).

**Problem 6 — Concatenation vs stacking.**  
Make two position time series $x_1(t)$ and $x_2(t)$. Use `np.concatenate` to form a single long series and `np.stack` to create an array with a new run axis. Explain the shape difference and how to index run 0 vs run 1 in the stacked version.

**Problem 7 — Building state arrays from pieces.**  
Using arrays $x(t)$, $y(t)$, $v_x(t)$, and $v_y(t)$, build a state matrix with columns $[x,y,v_x,v_y]$ using `np.column_stack`. Then split it back into separate 1D arrays and verify equality with `np.allclose`.

**Problem 8 — Repeat and tile practice.**  
Given a base array $b=[1,2,3]$, produce $[1,2,2,3,3,3]$ with `np.repeat` and $[1,2,3,1,2,3,1,2,3]$ with `np.tile`. Generalize to other patterns.


In [ ]:

# Workspace for Problem 1
import numpy as np
# TODO: your code here



<details>
<summary><strong>Solution</strong> (click to expand)</summary>

Compute arrays for position and velocity on a uniform time grid and stack into a state matrix with columns `[x, y, vx, vy]`.

```python
import numpy as np

# Parameters (example)
r0 = np.array([0.0, 1.0])         # initial position (m)
v0 = np.array([5.0, 6.0])         # initial velocity (m/s)
a  = np.array([0.2, -9.81])       # constant acceleration (m/s^2)

T = 2.0
N = 101
t = np.linspace(0, T, N)

tc = t[:, None]                   # (N,1) for broadcasting
v = v0 + a*tc                      # (N,2)
r = r0 + v0*tc + 0.5*a*(tc**2)    # (N,2)

state = np.column_stack([r, v])   # (N,4) -> [x, y, vx, vy]
print(state.shape)
print(state[:5])
```

</details>


In [ ]:

# Workspace for Problem 2
import numpy as np
# TODO: your code here



<details>
<summary><strong>Solution</strong> (click to expand)</summary>

Generate a projectile trajectory, estimate speed with `np.gradient`, and compute energies.

```python
import numpy as np
import matplotlib.pyplot as plt

m = 0.145       # kg (baseball)
g = 9.81
r0 = np.array([0.0, 0.0])
v0 = np.array([30.0, 20.0])

T = 5.0
N = 501
t = np.linspace(0, T, N)
dt = t[1] - t[0]

a = np.array([0.0, -g])
tc = t[:, None]
r = r0 + v0*tc + 0.5*a*(tc**2)          # (N,2)

# Keep samples with y >= 0
valid = r[:,1] >= 0
r = r[valid]
t = t[valid]

# Numerical velocity via gradient of position components
vx = np.gradient(r[:,0], t)
vy = np.gradient(r[:,1], t)
speed = np.sqrt(vx**2 + vy**2)

K = 0.5 * m * speed**2
U = m * g * r[:,1]
E = K + U

plt.figure(figsize=(6,3))
plt.plot(t, K, label='Kinetic K')
plt.plot(t, U, label='Potential U')
plt.plot(t, E, label='Total E')
plt.xlabel('time (s)'); plt.ylabel('energy (J)'); plt.legend();
```

</details>


In [ ]:

# Workspace for Problem 3
import numpy as np
# TODO: your code here



<details>
<summary><strong>Solution</strong> (click to expand)</summary>

Create arrays using each requested constructor and print value, shape, dtype.

```python
import numpy as np

rng = np.random.default_rng(0)

print('arange:', np.arange(0, 6, 2), np.arange(0,6,2).shape)
print('linspace:', np.linspace(0, 1, 5), np.linspace(0,1,5).shape)
print('logspace:', np.logspace(0, 3, 4, base=10.0))
print('geomspace:', np.geomspace(1, 1000, 4))

print('zeros:', np.zeros((2,3)).shape)
print('ones:', np.ones((2,3)).shape)
print('full:', np.full((2,3), 7).shape)

base = np.array([[1,2,3],[4,5,6]], dtype=float)
print('zeros_like dtype:', np.zeros_like(base).dtype)
print('ones_like dtype:', np.ones_like(base).dtype)
print('full_like(9):', np.full_like(base, 9).shape)

print('eye:
', np.eye(3))
print('diag:
', np.diag([1,2,3]))

print('random U:
', rng.random((2,3)))
print('normal:
', rng.normal(0,1,(2,3)))
print('integers:
', rng.integers(0,10,(2,3)))
```

</details>


In [ ]:

# Workspace for Problem 4
import numpy as np
# TODO: your code here



<details>
<summary><strong>Solution</strong> (click to expand)</summary>

Reshape a length-\(N\) array into different shapes and compare `ravel` vs `flatten`.

```python
import numpy as np

N = 12
x = np.arange(N)              # (12,)
col = x[:, None]              # (12,1)
row = x[None, :]              # (1,12)
M = x.reshape(3, 4)           # (3,4) since 3*4 = 12

rv = np.ravel(M)              # view when possible
fl = M.flatten()              # copy

print('x.shape, col.shape, row.shape, M.shape ->', x.shape, col.shape, row.shape, M.shape)
print('ravel shares data?', rv.base is not None)
print('flatten shares data?', fl.base is not None)

M[0,0] = 999
print('ravel reflects change?', rv[0] == 999)
print('flatten reflects change?', fl[0] == 999)
```

</details>


In [ ]:

# Workspace for Problem 5
import numpy as np
# TODO: your code here



<details>
<summary><strong>Solution</strong> (click to expand)</summary>

Demonstrate dtype conversions and check for information loss.

```python
import numpy as np

x64 = np.array([0.9, 1.1, 2.9, -3.7], dtype=np.float64)
xi = x64.astype(np.int32)            # truncates toward zero
x32 = x64.astype(np.float32)
back64 = x32.astype(np.float64)

print('x64:', x64, x64.dtype)
print('xi :', xi, xi.dtype)
print('x32:', x32, x32.dtype)
print('back64:', back64, back64.dtype)

# Information loss metrics
print('max abs error float32 vs float64:', np.max(np.abs(x64 - x32)))
print('restored error (back64 vs x64):', np.max(np.abs(back64 - x64)))
```

</details>


In [ ]:

# Workspace for Problem 6
import numpy as np
# TODO: your code here



<details>
<summary><strong>Solution</strong> (click to expand)</summary>

Create two time series, then `concatenate` (one long run) vs `stack` (new run axis).

```python
import numpy as np

# Two runs: same sampling but different signals
T = 2.0
N = 9
t = np.linspace(0, T, N)

x1 = np.sin(2*np.pi*0.5*t)
x2 = np.sin(2*np.pi*0.5*t + 0.5)

x_cat = np.concatenate([x1, x2])         # (2N,)
x_stk = np.stack([x1, x2], axis=0)       # (2, N)

print('concatenate ->', x_cat.shape)
print('stack       ->', x_stk.shape)
print('run0 first 3:', x_stk[0,:3])
print('run1 first 3:', x_stk[1,:3])
```

</details>


In [ ]:

# Workspace for Problem 7
import numpy as np
# TODO: your code here



<details>
<summary><strong>Solution</strong> (click to expand)</summary>

Build a state matrix and split it back out. Verify with `np.allclose`.

```python
import numpy as np

N = 6
t = np.linspace(0, 1, N)

x  = t**2
y  = 2*t
vx = np.gradient(x, t)
vy = np.gradient(y, t)

state = np.column_stack([x, y, vx, vy])

x2  = state[:, 0]
y2  = state[:, 1]
vx2 = state[:, 2]
vy2 = state[:, 3]

print('equal x  ?', np.allclose(x,  x2))
print('equal y  ?', np.allclose(y,  y2))
print('equal vx ?', np.allclose(vx, vx2))
print('equal vy ?', np.allclose(vy, vy2))
```

</details>


In [ ]:

# Workspace for Problem 8
import numpy as np
# TODO: your code here



<details>
<summary><strong>Solution</strong> (click to expand)</summary>

Use `repeat` and `tile`, then show parameterized variants.

```python
import numpy as np

b = np.array([1,2,3])
pat1 = np.repeat(b, repeats=[1,2,3])     # [1, 2,2, 3,3,3]
pat2 = np.tile(b, reps=3)                # [1,2,3,1,2,3,1,2,3]
print(pat1)
print(pat2)

# Parameterized helper: repeat each element k times
k = 4
print('repeat each element k times:', np.repeat(b, k))

# Parameterized helper: tile entire vector r times
r = 2
print('tile vector r times:', np.tile(b, r))
```

</details>
